name: Actualización Diaria de Datos

on:
  schedule:
    - cron: '0 9 * * *' # Se ejecuta cada día a las 09:00 UTC
  workflow_dispatch: # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: pip install pandas streamlit plotly

      - name: Ejecutar recolector
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python ranking_code.py

      - name: Guardar cambios en el repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add historico_top400_ranking.csv
          git commit -m "Actualización automática: $(date +'%Y-%m-%d')" || exit 0
          git push